replicaCount: 2

image:
  repository: ""   # 👈 จะถูก inject จาก GitHub Actions
  pullPolicy: IfNotPresent
  tag: ""          # 👈 จะใช้ commit SHA

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5

serviceAccount:
  create: true
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

httpRoute:
  enabled: false